apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-app
  namespace: argocd
spec:
  destination:
    namespace: demo-app
    server: https://kubernetes.default.svc
  project: demo-app
  sources:
  - repoURL: registry-1.docker.io/bitnamicharts
    chart: nginx
    targetRevision: 20.0.3
  syncPolicy:
    automated: {}
