apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io/background
spec:
  destination:
    namespace: ingress-nginx
    server: https://kubernetes.default.svc
  project: ingress-nginx
  sources:
  - repoURL: https://kubernetes.github.io/ingress-nginx
    chart: ingress-nginx
    targetRevision: 4.12.3
    helm:
      valueFiles:
      - $values/projects/ingress-nginx/values.yaml
  - repoURL: https://github.com/destngx/gitops.git
    targetRevision: main
    ref: values
  # Create custom ingress that will create ALB using Kustomize
  # - repoURL: https://github.com/destngx/gitops.git
  #   targetRevision: main
  #   path: projects/ingress-nginx/custom-ingress
  syncPolicy:
    automated: {}
    syncOptions:
    - ServerSideApply=true
