apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: telepresence
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: monitoring
  sources:
  - repoURL: ghcr.io/telepresenceio  # note: the oci:// syntax is not included.
    chart: telepresence-oss
    targetRevision: 2.22.4
    helm:
      valueFiles:
      - telepresence-values.yaml
      ignoreMissingValueFiles: true
  syncPolicy:
    automated: {}
