apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-apps-management
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io/background 
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: projects
    repoURL: https://github.com/destngx/gitops.git
    targetRevision: main
  syncPolicy:
    automated: {}

