apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
  - namespace.yaml

patches:
  - path: cluster-role.yaml
  - path: role.yaml
  - path: argocd-cm.yaml

images:
  - name: quay.io/argoproj/argocd
    newName: ghcr.io/argoproj/argo-cd/argocd
    newTag: 3.1.0-dbd8009f
